authors:
  karlipe:
    name: Karlipe Gomes
    description: DevOps Specialist
    url: https://www.linkedin.com/in/cfgomes/
    avatar: https://media.licdn.com/dms/image/v2/C4D03AQFIXHgqvqkmAg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1667855551215?e=1756944000&v=beta&t=Gb034MMCxFzEm2Ub38bJQhloI8QOardgBKE_AXf6Ppo
