authors:
  karlipe:
    name: Karlipe Gomes
    description: DevOps Specialist
    email: carlosfelipe.cbg@gmail.com
    url: https://www.linkedin.com/in/cfgomes/en/
    avatar: https://avatars.githubusercontent.com/u/8519235
