authors:
  karlipe:
    name: Karlipe Gomes
    description: DevOps Specialist
    url: https://www.linkedin.com/in/cfgomes/
    avatar: https://media.licdn.com/dms/image/v2/C4D03AQFIXHgqvqkmAg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1667855551215?e=1759968000&v=beta&t=9ktxrUEcx8TYfam-cEw2ill3w3Eq7kfzbCQXv7UjU6M
